/* 
 * ------------------------------------------------------------------------
 *
 *  Copyright (C) 2003 - 2013
 *  University of Konstanz, Germany and
 *  KNIME GmbH, Konstanz, Germany
 *  Website: http://www.knime.org; Email: contact@knime.org
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License, Version 3, as
 *  published by the Free Software Foundation.
 *
 *  This program is distributed in the hope that it will be useful, but
 *  WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, see <http://www.gnu.org/licenses>.
 *
 *  Additional permission under GNU GPL version 3 section 7:
 *
 *  KNIME interoperates with ECLIPSE solely via ECLIPSE's plug-in APIs.
 *  Hence, KNIME and ECLIPSE are both independent programs and are not
 *  derived from each other. Should, however, the interpretation of the
 *  GNU GPL Version 3 ("License") under any applicable laws result in
 *  KNIME and ECLIPSE being a combined program, KNIME GMBH herewith grants
 *  you the additional permission to use and propagate KNIME together with
 *  ECLIPSE with only the license terms in place for ECLIPSE applying to
 *  ECLIPSE and the GNU GPL Version 3 applying for KNIME, provided the
 *  license terms of ECLIPSE themselves allow for the respective use and
 *  propagation of ECLIPSE together with KNIME.
 *
 *  Additional permission relating to nodes for KNIME that extend the Node
 *  Extension (and in particular that are based on subclasses of NodeModel,
 *  NodeDialog, and NodeView) and that only interoperate with KNIME through
 *  standard APIs ("Nodes"):
 *  Nodes are deemed to be separate and independent programs and to not be
 *  covered works.  Notwithstanding anything to the contrary in the
 *  License, the License does not apply to Nodes, you are not required to
 *  license Nodes under the License, and you are granted a license to
 *  prepare and propagate Nodes, in each case even if such Nodes are
 *  propagated with or for interoperation with KNIME.  The owner of a Node
 *  may freely choose the license terms applicable to such Node, including
 *  when such Node is propagated with or for interoperation with KNIME.
 * -------------------------------------------------------------------
 */
package org.knime.core.util;

/**
 * This exception is thrown by the {@link DuplicateChecker} if a duplicate key
 * has been detected.
 * 
 * @author Thorsten Meinl, University of Konstanz
 */
public class DuplicateKeyException extends RuntimeException {
    private final String m_key;
    
    /**
     * Creates a new exception with predefined message.
     * 
     * @param key the duplicate key
     */
    public DuplicateKeyException(final String key) {
        this("Duplicate key detected: \"" + key + "\"", key); 
    }
    
    /**
     * Creates a new exception.
     * @param message The exception message, may or may not include 
     * <code>key</code>
     * @param key the duplicate key
     */
    public DuplicateKeyException(final String message, final String key) {
        super(message);
        m_key = key;
    }
    
    /** Creates new exception based on a reference exception (which may have 
     * been generated by a different thread).
     * @param cause The cause for this duplicate key exception.
     */
    public DuplicateKeyException(final DuplicateKeyException cause) {
        super(cause.getMessage(), cause);
        m_key = cause.m_key;
    }
    
    /**
     * Returns the duplicate key.
     * 
     * @return the key
     */
    public String getKey() {
        return m_key;
    }
    
}
