#!/bin/bash
#
# Start script for MacOS because the standard Eclipse launcher is unable to use any other JRE than the system's JRE
# 

SOURCE="$0"
SOURCE_DIR="$(dirname "$SOURCE")"
APP_DIR="$(cd -P "$SOURCE_DIR" && pwd)"
SOURCE="$APP_DIR/${SOURCE##*/}"
while [[ -h "$SOURCE" ]]; do
    SOURCE="$(readlink "$SOURCE")"
    APP_DIR="$APP_DIR/${SOURCE%/*}"
done
ECLIPSE_DIR="$APP_DIR/../../.."

declare -a VM_ARGS
declare -a APP_ARGS
JAVA=""
CLASSPATH=""
APPLICATION_OR_PRODUCT_SET=0
INI_FILE="$APP_DIR/${SOURCE##*/}".ini

readArguments() {
    local params=("$@")
    
    local i=0
    local inVmargs=0
    while [[ $i -lt ${#params[@]} ]]; do
        arg=${params[$i]}
        
        if [[ $inVmargs -gt 0 ]]; then
            VM_ARGS+=("$arg")
        elif [[ "$arg" == "-vmargs" ]]; then
            inVmargs=1
            VM_ARGS=()
        elif [[ "$arg" == "-vm" ]]; then
            JAVA=${params[i+1]}
            ((i++))
        elif [[ "$arg" == "-startup" ]]; then
            CLASSPATH="${params[i+1]}"
            ((i++))
        elif [[ "$arg" == "--launcher.ini" ]] ; then
        	INI_FILE=${params[i+1]}
        	((i++))
        elif [[ "$arg" == "--launcher.library" ]] || [[ "$arg" == "--launcher.timeout" ]] || \
        	 [[ "$arg" == "--launcher.XXMaxPermSize" ]]; then
        	echo "Launcher argument '$arg' ignored"
        	((i++)) # ...and its argument
        elif [[ "$arg" == --launcher.* ]]; then
        	echo "Launcher argument '$arg' ignored"
        else
            APP_ARGS+=("$arg")
        fi
        
        if [[ "$arg" == "-application" ]] || [[ "$arg" == "-product" ]]; then
            APPLICATION_OR_PRODUCT_SET=1
        fi
        ((i++)) 
    done
}


# detect java
if [[ -x "$ECLIPSE_DIR/jre/bin/java" ]]; then
    # start KNIME with the java in the jre folder
    JAVA="$ECLIPSE_DIR/jre/bin/java"
elif [[ -x "$ECLIPSE_DIR/jre/Home/bin/java" ]]; then
    # start KNIME with the java in the jre folder
    JAVA="$ECLIPSE_DIR/jre/Home/bin/java"
else
    JAVA=java
fi


# check for supported --launcher. arguments
readArguments "$@"
VM_ARGS=()
APP_ARGS=()

# extract parameters from Knime.ini
ALL_ARGUMENTS=( $(cat "$INI_FILE") )
readArguments "${ALL_ARGUMENTS[@]}"

# add command line parameters, they should override the parameters from the ini file
readArguments "$@"

VM_ARGS+=("-Declipse.vm=\"$JAVA\"")

if [[ $APPLICATION_OR_PRODUCT_SET -eq 0 ]]; then
    APP_ARGS+=("-product" "org.knime.product.KNIME_PRODUCT" "-name" "KNIME" "-showsplash" "600")
fi

if ! [[ -f "$CLASSPATH" ]]; then
    CLASSPATH="$APP_DIR/$CLASSPATH"
fi

# fire it up
LAST_PWD="$PWD"
cd "$APP_DIR"
"$JAVA" "${VM_ARGS[@]}" -classpath "$CLASSPATH" org.eclipse.equinox.launcher.Main "${APP_ARGS[@]}"
RET=$?
cd "$LAST_PWD"
if [[ $RET -eq 23 ]] || [[ $RET -eq 24 ]]; then
	exec "$SOURCE" "$@"
else
	exit $RET
fi
