bin.includes = knime-core-workbench.jar,\
               META-INF/,\
               LICENSE.txt,\
               CHANGELOG.md
jars.compile.order = knime-core-workbench.jar
source.knime-core-workbench.jar = src/
output.knime-core-workbench.jar = bin/
src.includes = LICENSE.txt
bin.excludes = maven.properties
