#!/bin/bash
#
# This script is run on the virtual build host
#

if [ -z "$TEMP"]; then
	export TEMP=/tmp
fi
if [ -z "$TMP" ]; then
	export TMP=$TEMP
fi

svn co https://bimsvn.inf.uni-konstanz.de/repository/bioml/trunk/KNIME_Deployment/org.knime.newbuild
cd org.knime.newbuild/scripts
./runTests
