#!/bin/bash

export LD_LIBRARY_PATH="/opt/VirtualBox"

/opt/VirtualBox/VBoxManage snapshot "KNIME openSuSE 10.2" discardcurrent -state
/opt/VirtualBox/VBoxManage startvm "KNIME openSuSE 10.2"
sleep 60
scp -P2222 -i knime_id_dsa nightly-tests knime@localhost:
ssh -p2222 -i knime_id_dsa knime@localhost "bash nightly-tests"
/opt/VirtualBox/VBoxManage controlvm "KNIME openSuSE 10.2" poweroff
