/*
 * ------------------------------------------------------------------------
 *
 *  Copyright (C) 2003 - 2013
 *  University of Konstanz, Germany and
 *  KNIME GmbH, Konstanz, Germany
 *  Website: http://www.knime.org; Email: contact@knime.org
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License, Version 3, as
 *  published by the Free Software Foundation.
 *
 *  This program is distributed in the hope that it will be useful, but
 *  WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, see <http://www.gnu.org/licenses>.
 *
 *  Additional permission under GNU GPL version 3 section 7:
 *
 *  KNIME interoperates with ECLIPSE solely via ECLIPSE's plug-in APIs.
 *  Hence, KNIME and ECLIPSE are both independent programs and are not
 *  derived from each other. Should, however, the interpretation of the
 *  GNU GPL Version 3 ("License") under any applicable laws result in
 *  KNIME and ECLIPSE being a combined program, KNIME GMBH herewith grants
 *  you the additional permission to use and propagate KNIME together with
 *  ECLIPSE with only the license terms in place for ECLIPSE applying to
 *  ECLIPSE and the GNU GPL Version 3 applying for KNIME, provided the
 *  license terms of ECLIPSE themselves allow for the respective use and
 *  propagation of ECLIPSE together with KNIME.
 *
 *  Additional permission relating to nodes for KNIME that extend the Node
 *  Extension (and in particular that are based on subclasses of NodeModel,
 *  NodeDialog, and NodeView) and that only interoperate with KNIME through
 *  standard APIs ("Nodes"):
 *  Nodes are deemed to be separate and independent programs and to not be
 *  covered works.  Notwithstanding anything to the contrary in the
 *  License, the License does not apply to Nodes, you are not required to
 *  license Nodes under the License, and you are granted a license to
 *  prepare and propagate Nodes, in each case even if such Nodes are
 *  propagated with or for interoperation with KNIME. The owner of a Node
 *  may freely choose the license terms applicable to such Node, including
 *  when such Node is propagated with or for interoperation with KNIME.
 * ------------------------------------------------------------------------
 *
 */
package org.knime.core.node.port.image;

import javax.swing.JComponent;
import javax.swing.JLabel;

import org.knime.core.data.DataType;
import org.knime.core.node.InvalidSettingsException;
import org.knime.core.node.ModelContentRO;
import org.knime.core.node.ModelContentWO;
import org.knime.core.node.port.AbstractSimplePortObjectSpec;

/** Port object spec to an {@link ImagePortObject}. It only wraps the
 * {@link DataType} of the cell that would be generated by the port objects
 * {@link ImagePortObject#toDataCell()} method.
 *
 * @author Thomas Gabriel, KNIME.com, Zurich, Switzerland
 */
public final class ImagePortObjectSpec extends AbstractSimplePortObjectSpec {

    private DataType m_type;

    /** Constructor to be used. Init spec with argument type.
     * @param type The type of the cell (see class description for details).
     */
    public ImagePortObjectSpec(final DataType type) {
        if (type == null) {
            throw new NullPointerException("Argument must not be null.");
        }
        m_type = type;
    }

    /** <b>Framework constructor - do not use.</b> The constructor is required
     * by the super class implementation to restort the content. Client code
     * must not call this constructor. */
    public ImagePortObjectSpec() {
        // no op
    }

    /** Get the {@link DataType} of the cell that will be generated by the
     * port objects {@link ImagePortObject#toDataCell()} method.
     * @return The type of the cell, never null. */
    public DataType getDataType() {
        return m_type;
    }

    /** {@inheritDoc} */
    @Override
    public JComponent[] getViews() {
        JLabel l = new JLabel("Image of type \"" + getDataType() + "\"");
        l.setName("Image Spec");
        return new JComponent[]{l};
    }

    /** {@inheritDoc} */
    @Override
    protected void load(
            final ModelContentRO model) throws InvalidSettingsException {
        m_type = DataType.load(model);
    }

    /** {@inheritDoc} */
    @Override
    protected void save(final ModelContentWO model) {
        m_type.save(model);
    }

}
