/*
 * ------------------------------------------------------------------------
 *
 *  Copyright by KNIME AG, Zurich, Switzerland
 *  Website: http://www.knime.com; Email: contact@knime.com
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License, Version 3, as
 *  published by the Free Software Foundation.
 *
 *  This program is distributed in the hope that it will be useful, but
 *  WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, see <http://www.gnu.org/licenses>.
 *
 *  Additional permission under GNU GPL version 3 section 7:
 *
 *  KNIME interoperates with ECLIPSE solely via ECLIPSE's plug-in APIs.
 *  Hence, KNIME and ECLIPSE are both independent programs and are not
 *  derived from each other. Should, however, the interpretation of the
 *  GNU GPL Version 3 ("License") under any applicable laws result in
 *  KNIME and ECLIPSE being a combined program, KNIME AG herewith grants
 *  you the additional permission to use and propagate KNIME together with
 *  ECLIPSE with only the license terms in place for ECLIPSE applying to
 *  ECLIPSE and the GNU GPL Version 3 applying for KNIME, provided the
 *  license terms of ECLIPSE themselves allow for the respective use and
 *  propagation of ECLIPSE together with KNIME.
 *
 *  Additional permission relating to nodes for KNIME that extend the Node
 *  Extension (and in particular that are based on subclasses of NodeModel,
 *  NodeDialog, and NodeView) and that only interoperate with KNIME through
 *  standard APIs ("Nodes"):
 *  Nodes are deemed to be separate and independent programs and to not be
 *  covered works.  Notwithstanding anything to the contrary in the
 *  License, the License does not apply to Nodes, you are not required to
 *  license Nodes under the License, and you are granted a license to
 *  prepare and propagate Nodes, in each case even if such Nodes are
 *  propagated with or for interoperation with KNIME.  The owner of a Node
 *  may freely choose the license terms applicable to such Node, including
 *  when such Node is propagated with or for interoperation with KNIME.
 * ---------------------------------------------------------------------
 *
 * History
 *   22 Jun 2022 (carlwitt): created
 */
package org.knime.core.telemetry;

import java.util.Optional;

import org.knime.core.node.workflow.NativeNodeContainer;

/**
 * For use in a {@link NativeNodeContainer}. Since the container can execute the node multiple times, instances of this
 * class can be used to generate the according {@link NodeExecutionSpan}s.
 *
 * @author Carl Witt, KNIME AG, Zurich, Switzerland
 */
public class NodeExecutionTelemetry {

    /**
     * Parent span for all {@link NodeExecutionSpan}s generated by this instance.
     */
    private final WorkflowSessionSpan m_workflowSessionSpan;

    /**
     * The span name for all {@link NodeExecutionSpan}s generated by this instance.
     */
    private final String m_nodeName;

    /**
     * If present, the span is currently recording.
     *
     * @see #startExecution()
     * @see #stopExecution()
     */
    private Optional<NodeExecutionSpan> m_currentSpan = Optional.empty();

    /**
     * @param nodeName
     * @param workflowSessionSpan
     */
    public NodeExecutionTelemetry(final String nodeName, final WorkflowSessionSpan workflowSessionSpan) {
        m_workflowSessionSpan = workflowSessionSpan;
        m_nodeName = nodeName;
    }

    /**
     * Start a new span in the containing workflow span marking the beginning of the node execution.
     *
     * @return the telemetry object for a native node execution. If none is present, calls {@link #startExecution()}.
     */
    public NodeExecutionSpan startExecution() {
        m_currentSpan = Optional.of(new NodeExecutionSpan(m_nodeName, m_workflowSessionSpan.getSpan()));
        return m_currentSpan.get();
    }

    /**
     * Stops the current span, marking the end of one execution of a particular {@link NativeNodeContainer}.
     */
    public void stopExecution() {
        m_currentSpan.orElseThrow(IllegalStateException::new);
        m_currentSpan.get().end();
        m_currentSpan = Optional.empty();
    }

    /**
     * @return the telemetry object for a native node execution. If none is present, calls {@link #startExecution()}.
     */
    public NodeExecutionSpan getCurrentSpan() {
        if (m_currentSpan.isEmpty()) {
            return startExecution();
        }
        return m_currentSpan.get();
    }

}
